### ISSUE TITLE
Thumbnail image for MakeCode Arcade homescreen

### ISSUE THREAD

**Issue by ganicke** [UnsignedArduino/Fishy-Fishy-Cross-my-Ocean#2]
Hi, could you add an image (`thumb.png`) to https://github.com/UnsignedArduino/Fishy-Fishy-Cross-my-Ocean/tree/master/.github/makecode as a thumbnail for the Game Jam gallery entry for this game? We need an image for the card and they aren't generated for projects in GitHub. Maybe something like (300x200 ish):

![image](https://user-images.githubusercontent.com/27789908/109066094-64547180-76a1-11eb-9105-acf12ed3ce22.png)

We have an empty image on the card at the moment:

![image](https://user-images.githubusercontent.com/27789908/109066631-2c99f980-76a2-11eb-8508-2213f5caf5ca.png)

Thanks.

**Comment by UnsignedArduino** [comment]
Hey @ganicke is this okay? It's 475x356, but I can resize it if you want. I just took a picture using Arcade's take picture button and cropped it.
![arcade-Fishy-Fishy-Cross-my-Ocean](https://user-images.githubusercontent.com/38868705/109067723-e3a36e80-76bc-11eb-96eb-ecc21edf4fcf.png)

**Comment by ganicke** [comment]
Yea, that's fine. Thanks!

**Comment by UnsignedArduino** [comment]
Done. Hopefully, that works 👍

**Comment by ganicke** [comment]
![image](https://user-images.githubusercontent.com/27789908/109070285-26f2e280-76a7-11eb-8ac1-094edb554512.png)
